#!/usr/bin/env bash
# Post-implementation hook for documentation updates
# Generated by document-spring-project skill

# Detectar archivos modificados en src/main/ (no tests)
RECENT_FILES=$(git diff HEAD~1 HEAD --name-only 2>/dev/null | grep "^src/main/" || echo "")

if [ -z "$RECENT_FILES" ]; then
    exit 0
fi

# Filtrar cambios relevantes (controllers, services, entities, config)
RELEVANT_CHANGES=$(echo "$RECENT_FILES" | grep -E "(Controller|Service|Repository|Entity|Config)\.java$" || echo "")

if [ -z "$RELEVANT_CHANGES" ]; then
    exit 0
fi

# Detectar último commit de docs
LAST_DOC_COMMIT=$(git log -1 --format="%H" -- CLAUDE.md .claude/rules/ docs/ README.md 2>/dev/null)

if [ -z "$LAST_DOC_COMMIT" ]; then
    # Primera vez, no recordar aún
    exit 0
fi

# Contar cambios desde última actualización de docs
CHANGES_COUNT=$(git diff "$LAST_DOC_COMMIT"..HEAD --name-only -- src/main/ | wc -l | tr -d ' ')

if [ "$CHANGES_COUNT" -lt 3 ]; then
    # Pocos cambios, no vale la pena recordar aún
    exit 0
fi

# Mostrar recordatorio
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📝 Recordatorio: Documentación pendiente"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Se detectaron $CHANGES_COUNT archivos modificados en src/main/ desde la última actualización de docs."
echo ""
echo "Archivos modificados:"
echo "$RELEVANT_CHANGES" | head -5 | sed 's/^/  • /'
[ "$CHANGES_COUNT" -gt 5 ] && echo "  ... y $(($CHANGES_COUNT - 5)) más"
echo ""
echo "💡 Sugerencia: Actualiza la documentación"
echo "   Ejecuta: /docs"
echo "   Y elige: 2 (Análisis Incremental)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
